### ISSUE TITLE
Java compilation error

### ISSUE THREAD

**Issue by vergenzt** [cs2340-group3/m2-git-and-gradle#5]
@z3t1, I'm getting a compilation error at [line 38 of Person4.java](https://github.com/cs2340-group3/m2-git-and-gradle/blob/master/src/main/java/edu/gatech/oad/antlab/person/Person4.java#L38), "Type mismatch: cannot convert from int to char."

Did it compile under a different Java version or something? I'm on Java 1.7.

**Comment by z3t1** [comment]
@vergenzt Fixed. Now it compiles.
